// Common countries for international students
export const COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Argentina', 'Australia', 'Austria',
  'Bangladesh', 'Belgium', 'Brazil', 'Bulgaria',
  'Cambodia', 'Cameroon', 'Canada', 'Chile', 'Colombia', 'Congo', 'Costa Rica',
  'Denmark', 'Egypt', 'Ethiopia', 'Finland', 'France',
  'Germany', 'Ghana', 'Greece',
  'Hungary',
  'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Italy',
  'Japan', 'Jordan',
  'Kazakhstan', 'Kenya', 'Kuwait',
  'Laos', 'Lebanon', 'Libya',
  'Malaysia', 'Mexico', 'Mongolia', 'Morocco', 'Myanmar',
  'Nepal', 'Netherlands', 'New Zealand', 'Nigeria', 'Norway',
  'Pakistan', 'Palestine', 'Peru', 'Philippines', 'Poland', 'Portugal',
  'Qatar',
  'Romania', 'Russia', 'Rwanda',
  'Saudi Arabia', 'Senegal', 'Singapore', 'Somalia', 'South Africa', 'South Korea', 'Spain', 'Sri Lanka', 'Sudan', 'Sweden', 'Switzerland', 'Syria',
  'Taiwan', 'Tanzania', 'Thailand', 'Tunisia', 'Turkey',
  'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uzbekistan',
  'Venezuela', 'Vietnam',
  'Yemen',
  'Zambia', 'Zimbabwe'
];

// Country codes for phone numbers
export const COUNTRY_CODES = [
  { code: '+93', country: 'Afghanistan', id: 'AF' },
  { code: '+355', country: 'Albania', id: 'AL' },
  { code: '+213', country: 'Algeria', id: 'DZ' },
  { code: '+54', country: 'Argentina', id: 'AR' },
  { code: '+61', country: 'Australia', id: 'AU' },
  { code: '+43', country: 'Austria', id: 'AT' },
  { code: '+880', country: 'Bangladesh', id: 'BD' },
  { code: '+32', country: 'Belgium', id: 'BE' },
  { code: '+55', country: 'Brazil', id: 'BR' },
  { code: '+359', country: 'Bulgaria', id: 'BG' },
  { code: '+855', country: 'Cambodia', id: 'KH' },
  { code: '+237', country: 'Cameroon', id: 'CM' },
  { code: '+1', country: 'Canada', id: 'CA' },
  { code: '+56', country: 'Chile', id: 'CL' },
  { code: '+86', country: 'China', id: 'CN' },
  { code: '+57', country: 'Colombia', id: 'CO' },
  { code: '+243', country: 'Congo', id: 'CD' },
  { code: '+506', country: 'Costa Rica', id: 'CR' },
  { code: '+45', country: 'Denmark', id: 'DK' },
  { code: '+20', country: 'Egypt', id: 'EG' },
  { code: '+251', country: 'Ethiopia', id: 'ET' },
  { code: '+358', country: 'Finland', id: 'FI' },
  { code: '+33', country: 'France', id: 'FR' },
  { code: '+49', country: 'Germany', id: 'DE' },
  { code: '+233', country: 'Ghana', id: 'GH' },
  { code: '+30', country: 'Greece', id: 'GR' },
  { code: '+36', country: 'Hungary', id: 'HU' },
  { code: '+91', country: 'India', id: 'IN' },
  { code: '+62', country: 'Indonesia', id: 'ID' },
  { code: '+98', country: 'Iran', id: 'IR' },
  { code: '+964', country: 'Iraq', id: 'IQ' },
  { code: '+353', country: 'Ireland', id: 'IE' },
  { code: '+39', country: 'Italy', id: 'IT' },
  { code: '+81', country: 'Japan', id: 'JP' },
  { code: '+962', country: 'Jordan', id: 'JO' },
  { code: '+7', country: 'Kazakhstan', id: 'KZ' },
  { code: '+254', country: 'Kenya', id: 'KE' },
  { code: '+965', country: 'Kuwait', id: 'KW' },
  { code: '+856', country: 'Laos', id: 'LA' },
  { code: '+961', country: 'Lebanon', id: 'LB' },
  { code: '+218', country: 'Libya', id: 'LY' },
  { code: '+60', country: 'Malaysia', id: 'MY' },
  { code: '+52', country: 'Mexico', id: 'MX' },
  { code: '+976', country: 'Mongolia', id: 'MN' },
  { code: '+212', country: 'Morocco', id: 'MA' },
  { code: '+95', country: 'Myanmar', id: 'MM' },
  { code: '+977', country: 'Nepal', id: 'NP' },
  { code: '+31', country: 'Netherlands', id: 'NL' },
  { code: '+64', country: 'New Zealand', id: 'NZ' },
  { code: '+234', country: 'Nigeria', id: 'NG' },
  { code: '+47', country: 'Norway', id: 'NO' },
  { code: '+92', country: 'Pakistan', id: 'PK' },
  { code: '+970', country: 'Palestine', id: 'PS' },
  { code: '+51', country: 'Peru', id: 'PE' },
  { code: '+63', country: 'Philippines', id: 'PH' },
  { code: '+48', country: 'Poland', id: 'PL' },
  { code: '+351', country: 'Portugal', id: 'PT' },
  { code: '+974', country: 'Qatar', id: 'QA' },
  { code: '+40', country: 'Romania', id: 'RO' },
  { code: '+7', country: 'Russia', id: 'RU' },
  { code: '+250', country: 'Rwanda', id: 'RW' },
  { code: '+966', country: 'Saudi Arabia', id: 'SA' },
  { code: '+221', country: 'Senegal', id: 'SN' },
  { code: '+65', country: 'Singapore', id: 'SG' },
  { code: '+252', country: 'Somalia', id: 'SO' },
  { code: '+27', country: 'South Africa', id: 'ZA' },
  { code: '+82', country: 'South Korea', id: 'KR' },
  { code: '+34', country: 'Spain', id: 'ES' },
  { code: '+94', country: 'Sri Lanka', id: 'LK' },
  { code: '+249', country: 'Sudan', id: 'SD' },
  { code: '+46', country: 'Sweden', id: 'SE' },
  { code: '+41', country: 'Switzerland', id: 'CH' },
  { code: '+963', country: 'Syria', id: 'SY' },
  { code: '+886', country: 'Taiwan', id: 'TW' },
  { code: '+255', country: 'Tanzania', id: 'TZ' },
  { code: '+66', country: 'Thailand', id: 'TH' },
  { code: '+216', country: 'Tunisia', id: 'TN' },
  { code: '+90', country: 'Turkey', id: 'TR' },
  { code: '+256', country: 'Uganda', id: 'UG' },
  { code: '+380', country: 'Ukraine', id: 'UA' },
  { code: '+971', country: 'UAE', id: 'AE' },
  { code: '+44', country: 'UK', id: 'GB' },
  { code: '+1', country: 'USA', id: 'US' },
  { code: '+998', country: 'Uzbekistan', id: 'UZ' },
  { code: '+58', country: 'Venezuela', id: 'VE' },
  { code: '+84', country: 'Vietnam', id: 'VN' },
  { code: '+967', country: 'Yemen', id: 'YE' },
  { code: '+260', country: 'Zambia', id: 'ZM' },
  { code: '+263', country: 'Zimbabwe', id: 'ZW' },
];

// Common intake periods
export const INTAKE_PERIODS = [
  'September 2025',
  'March 2026',
  'September 2026',
  'March 2027',
  'September 2027',
];
